theme: jekyll-theme-slate
markdown: kramdown

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

include:
  - assets/css/custom.css
  - assets/images/favicon.ico
  - status.md
